version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: "all"
    groups:
      npm:
        patterns:
          - "*"
