{
  "formatVersion": "1.1",
  "component": {
    "group": "top.yukonga.miuix.kmp",
    "module": "miuix",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20-RC2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "dev.chrisbanes.haze",
          "module": "haze",
          "version": {
            "requires": "0.9.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-metadata-0.0.1.jar",
          "url": "miuix-0.0.1.jar",
          "size": 24641,
          "sha512": "9cafbc629584376f731ddc5a0647dec0726911d542c083f31588dcef2e4af9ae624f70e457537bbf1d3d404728619874677f406f7753ee5f80fc59b5e29a8536",
          "sha256": "b46a1309f9dbb74325c0b53e514afc92daa57ec5cdd243ad9555fc0b4a324282",
          "sha1": "0460a06479ba957d5765e84afc2ae61fdbcf4b59",
          "md5": "b2169d18160e850c04cf645fd5bf62d7"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../miuix-android/0.0.1/miuix-android-0.0.1.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-android",
        "version": "0.0.1"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../miuix-android/0.0.1/miuix-android-0.0.1.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-android",
        "version": "0.0.1"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../miuix-desktop/0.0.1/miuix-desktop-0.0.1.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-desktop",
        "version": "0.0.1"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../miuix-desktop/0.0.1/miuix-desktop-0.0.1.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-desktop",
        "version": "0.0.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../miuix-iosarm64/0.0.1/miuix-iosarm64-0.0.1.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-iosarm64",
        "version": "0.0.1"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../miuix-iosarm64/0.0.1/miuix-iosarm64-0.0.1.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-iosarm64",
        "version": "0.0.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../miuix-iosarm64/0.0.1/miuix-iosarm64-0.0.1.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-iosarm64",
        "version": "0.0.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../miuix-iossimulatorarm64/0.0.1/miuix-iossimulatorarm64-0.0.1.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-iossimulatorarm64",
        "version": "0.0.1"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../miuix-iossimulatorarm64/0.0.1/miuix-iossimulatorarm64-0.0.1.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-iossimulatorarm64",
        "version": "0.0.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../miuix-iossimulatorarm64/0.0.1/miuix-iossimulatorarm64-0.0.1.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-iossimulatorarm64",
        "version": "0.0.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../miuix-iosx64/0.0.1/miuix-iosx64-0.0.1.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-iosx64",
        "version": "0.0.1"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../miuix-iosx64/0.0.1/miuix-iosx64-0.0.1.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-iosx64",
        "version": "0.0.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../miuix-iosx64/0.0.1/miuix-iosx64-0.0.1.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-iosx64",
        "version": "0.0.1"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../miuix-wasm-js/0.0.1/miuix-wasm-js-0.0.1.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-wasm-js",
        "version": "0.0.1"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../miuix-wasm-js/0.0.1/miuix-wasm-js-0.0.1.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-wasm-js",
        "version": "0.0.1"
      }
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../miuix-wasm-js/0.0.1/miuix-wasm-js-0.0.1.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-wasm-js",
        "version": "0.0.1"
      }
    }
  ]
}
