{
  "formatVersion": "1.1",
  "component": {
    "url": "../../miuix/0.0.1/miuix-0.0.1.module",
    "group": "top.yukonga.miuix.kmp",
    "module": "miuix",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20-RC2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "dev.chrisbanes.haze",
          "module": "haze",
          "version": {
            "requires": "0.9.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "miuix.klib",
          "url": "miuix-iosx64-0.0.1.klib",
          "size": 278707,
          "sha512": "73ba0ca7287538a9019bb30d50b699cbacf7c3d3f10ce779489ae385c8b527d8008f770a02cf3fc12d2346512991cd2416a412822d0e7918382a1fd21f4d89f0",
          "sha256": "e31fcf07002a099b9517ccfe89bc83bb0afc030cd07431f2a7afd70465923e69",
          "sha1": "231182ce939d857c9a775224e527a19767d1e152",
          "md5": "4b2b42e8b28af4c8375b783dda53c14a"
        }
      ]
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20-RC2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "dev.chrisbanes.haze",
          "module": "haze",
          "version": {
            "requires": "0.9.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-0.0.1.kotlin_resources.zip",
          "url": "miuix-iosx64-0.0.1-kotlin_resources.kotlin_resources.zip",
          "size": 2826,
          "sha512": "ec77c5eff354ff01cca4d873852178009ea24bcb3653f31368d140b546460851627032719ca234711d107956f33c7bb5d019d5bf93cfd920528b065b47dc028f",
          "sha256": "5f479941a070a31143af592b667428a6d05de093f5bf66206e83e7ecb333963d",
          "sha1": "f886e8e2f8e1600fe8f082e665dc8dbf00d9e2f8",
          "md5": "aa5542e8d107703a1566ae5e1f25e473"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20-RC2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "dev.chrisbanes.haze",
          "module": "haze",
          "version": {
            "requires": "0.9.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-iosx64-0.0.1-metadata.jar",
          "url": "miuix-iosx64-0.0.1-metadata.jar",
          "size": 4060,
          "sha512": "24a6443ba7597accf7ac454ef6aeb16cabc57ffb8fcb1e580fa721ccaaeba0e71ef3ea1dec1064c65d867e0448f5a159663e813c85077fda39379b6af753b7ce",
          "sha256": "3df0b6d338c472ebf96138dceb1caaeb96c1eaa4d4d4676bf572b7198238277c",
          "sha1": "a80a20c7d31d2ba2cf34bc04ced352ddc5b73fc9",
          "md5": "06ea70b43b66b6cf71578427e4fa941e"
        }
      ]
    }
  ]
}
