{
  "formatVersion": "1.1",
  "component": {
    "url": "../../miuix/0.0.1/miuix-0.0.1.module",
    "group": "top.yukonga.miuix.kmp",
    "module": "miuix",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20-RC2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "dev.chrisbanes.haze",
          "module": "haze",
          "version": {
            "requires": "0.9.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "miuix.klib",
          "url": "miuix-iosarm64-0.0.1.klib",
          "size": 298416,
          "sha512": "47e70537dedad697a353c8007734137b7cee0f60065fe6d67b0a256af0635c7cbed1dd7d80eadf9fd9a24aa17083c7b84d08ae4515d425c33882cb75c09679b5",
          "sha256": "187f5d6527677feeb0d3aaf5efdef3329c99f3f84e84403e260d90bff0c262d5",
          "sha1": "7e42bf07821037eea16ece3d468d4cbd59dc144a",
          "md5": "506be645a8cdca137a86f0ab7eb999e7"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "miuix-iosarm64-0.0.1-sources.jar",
          "url": "miuix-iosarm64-0.0.1-sources.jar",
          "size": 57594,
          "sha512": "4cf8c1f44c5e4939be31ae150d48583f879853511ec3ace344a03c20cf51600081bd9c3324914502db899b8cfb20cd6ce0eeb2b38a273482e0a346f2e24e0136",
          "sha256": "052090b1596fcfb50687e498b37b4bfdd7fe6faf8ae608eaef5019d718198ef4",
          "sha1": "d13f5a9d9989d6bf16933eeaa3d12af49fe0ddd8",
          "md5": "05e07299bc34eff75e8da5fce12ba951"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20-RC2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "dev.chrisbanes.haze",
          "module": "haze",
          "version": {
            "requires": "0.9.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-0.0.1.kotlin_resources.zip",
          "url": "miuix-iosarm64-0.0.1-kotlin_resources.kotlin_resources.zip",
          "size": 2826,
          "sha512": "ec77c5eff354ff01cca4d873852178009ea24bcb3653f31368d140b546460851627032719ca234711d107956f33c7bb5d019d5bf93cfd920528b065b47dc028f",
          "sha256": "5f479941a070a31143af592b667428a6d05de093f5bf66206e83e7ecb333963d",
          "sha1": "f886e8e2f8e1600fe8f082e665dc8dbf00d9e2f8",
          "md5": "aa5542e8d107703a1566ae5e1f25e473"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20-RC2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "dev.chrisbanes.haze",
          "module": "haze",
          "version": {
            "requires": "0.9.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-iosarm64-0.0.1-metadata.jar",
          "url": "miuix-iosarm64-0.0.1-metadata.jar",
          "size": 4060,
          "sha512": "24a6443ba7597accf7ac454ef6aeb16cabc57ffb8fcb1e580fa721ccaaeba0e71ef3ea1dec1064c65d867e0448f5a159663e813c85077fda39379b6af753b7ce",
          "sha256": "3df0b6d338c472ebf96138dceb1caaeb96c1eaa4d4d4676bf572b7198238277c",
          "sha1": "a80a20c7d31d2ba2cf34bc04ced352ddc5b73fc9",
          "md5": "06ea70b43b66b6cf71578427e4fa941e"
        }
      ]
    }
  ]
}
