{
  "formatVersion": "1.1",
  "component": {
    "url": "../../miuix/0.0.1/miuix-0.0.1.module",
    "group": "top.yukonga.miuix.kmp",
    "module": "miuix",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20-RC2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "dev.chrisbanes.haze",
          "module": "haze",
          "version": {
            "requires": "0.9.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "miuix.klib",
          "url": "miuix-iosarm64-0.0.1.klib",
          "size": 299058,
          "sha512": "29e2abce97f7d53bd863c0f1553dfa8fdfc2616a5470714ebf46fa8542abe90d952784f02214637b94ab8c0ecf07a4c8dc04235c94170d8fa2cb1ca9d2d13447",
          "sha256": "2946ae4b0cde12afc03bbaa1e719a246ad456c02195eee64695943fca5b47b5f",
          "sha1": "ab17fbd13308f4199fc767e3ee43c6170a0d901c",
          "md5": "80f3f4466e8e0c568a23f36236f735a7"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "miuix-iosarm64-0.0.1-sources.jar",
          "url": "miuix-iosarm64-0.0.1-sources.jar",
          "size": 57573,
          "sha512": "9bdc189e243cc7c8c3b77a28c6456073029cc7cc9289991ff1f9d226982b8d7227fe18807326934519faf573e9f2b90d6432789c3bef69721c77022d00dba8e1",
          "sha256": "3d293943613c3a3adc32bed05ebc573e66f7bc3488920328a34db2df50afdeda",
          "sha1": "b1288531dc9032c6da16c70250b435dcdc814d94",
          "md5": "59548bf30a156b6128d51d99a27ced8d"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20-RC2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "dev.chrisbanes.haze",
          "module": "haze",
          "version": {
            "requires": "0.9.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-0.0.1.kotlin_resources.zip",
          "url": "miuix-iosarm64-0.0.1-kotlin_resources.kotlin_resources.zip",
          "size": 2826,
          "sha512": "ec77c5eff354ff01cca4d873852178009ea24bcb3653f31368d140b546460851627032719ca234711d107956f33c7bb5d019d5bf93cfd920528b065b47dc028f",
          "sha256": "5f479941a070a31143af592b667428a6d05de093f5bf66206e83e7ecb333963d",
          "sha1": "f886e8e2f8e1600fe8f082e665dc8dbf00d9e2f8",
          "md5": "aa5542e8d107703a1566ae5e1f25e473"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20-RC2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "dev.chrisbanes.haze",
          "module": "haze",
          "version": {
            "requires": "0.9.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-iosarm64-0.0.1-metadata.jar",
          "url": "miuix-iosarm64-0.0.1-metadata.jar",
          "size": 4060,
          "sha512": "24a6443ba7597accf7ac454ef6aeb16cabc57ffb8fcb1e580fa721ccaaeba0e71ef3ea1dec1064c65d867e0448f5a159663e813c85077fda39379b6af753b7ce",
          "sha256": "3df0b6d338c472ebf96138dceb1caaeb96c1eaa4d4d4676bf572b7198238277c",
          "sha1": "a80a20c7d31d2ba2cf34bc04ced352ddc5b73fc9",
          "md5": "06ea70b43b66b6cf71578427e4fa941e"
        }
      ]
    }
  ]
}
