{
  "formatVersion": "1.1",
  "component": {
    "url": "../../miuix/0.0.1/miuix-0.0.1.module",
    "group": "top.yukonga.miuix.kmp",
    "module": "miuix",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20-RC2"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-desktop-0.0.1.jar",
          "url": "miuix-desktop-0.0.1.jar",
          "size": 364480,
          "sha512": "6e01ba787313b83514ac4b072e4a80043e3ca4f9699d072c2caff5ec9df3bd9cb97379f459e1900ae749f04647040150daa9c424c58f4afeca93728ecd4dcf53",
          "sha256": "6e3d0ff38f6f5c647e3ab4b99be85d0aba4fcd53a2633187cafe113a13a4655e",
          "sha1": "9dd421ecb8edda501572094643708d41f5cc9402",
          "md5": "bc4563acec81a659aa6cbadbd9fbe51b"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20-RC2"
          }
        },
        {
          "group": "org.jetbrains.compose.desktop",
          "module": "desktop-jvm-macos-arm64",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "dev.chrisbanes.haze",
          "module": "haze",
          "version": {
            "requires": "0.9.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-desktop-0.0.1.jar",
          "url": "miuix-desktop-0.0.1.jar",
          "size": 364480,
          "sha512": "6e01ba787313b83514ac4b072e4a80043e3ca4f9699d072c2caff5ec9df3bd9cb97379f459e1900ae749f04647040150daa9c424c58f4afeca93728ecd4dcf53",
          "sha256": "6e3d0ff38f6f5c647e3ab4b99be85d0aba4fcd53a2633187cafe113a13a4655e",
          "sha1": "9dd421ecb8edda501572094643708d41f5cc9402",
          "md5": "bc4563acec81a659aa6cbadbd9fbe51b"
        }
      ]
    }
  ]
}
