{
  "formatVersion": "1.1",
  "component": {
    "url": "../../miuix/0.0.1/miuix-0.0.1.module",
    "group": "top.yukonga.miuix.kmp",
    "module": "miuix",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20-RC2"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-desktop-0.0.1.jar",
          "url": "miuix-desktop-0.0.1.jar",
          "size": 376295,
          "sha512": "663765b07bcaa0058eb316a3590ae34432b65a2d90290743d0c1320ff6c2f9b040e30f04fc0241f4e562dd3cc92e7d56834cd03427bf02446735db22bdd0e234",
          "sha256": "0ea6274a3c3ea7efcecbbbf12d8edd030f50022b28ba046b452946777943f61e",
          "sha1": "4171f7a1e1c04156d232b56d91d0a86b26e49d2e",
          "md5": "96a3932b1a0188d73f6072ea17c247b9"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20-RC2"
          }
        },
        {
          "group": "org.jetbrains.compose.desktop",
          "module": "desktop-jvm-macos-arm64",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "dev.chrisbanes.haze",
          "module": "haze",
          "version": {
            "requires": "0.9.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-desktop-0.0.1.jar",
          "url": "miuix-desktop-0.0.1.jar",
          "size": 376295,
          "sha512": "663765b07bcaa0058eb316a3590ae34432b65a2d90290743d0c1320ff6c2f9b040e30f04fc0241f4e562dd3cc92e7d56834cd03427bf02446735db22bdd0e234",
          "sha256": "0ea6274a3c3ea7efcecbbbf12d8edd030f50022b28ba046b452946777943f61e",
          "sha1": "4171f7a1e1c04156d232b56d91d0a86b26e49d2e",
          "md5": "96a3932b1a0188d73f6072ea17c247b9"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "miuix-desktop-0.0.1-sources.jar",
          "url": "miuix-desktop-0.0.1-sources.jar",
          "size": 57234,
          "sha512": "e038b02a5d44f7f919daf893d2d92cc65b7b451e7a3a031e7e80fc96cf0bba284e273bebbe0dd92f315ebb249272437d8da82ac261fbd75993e3b4598db18e2d",
          "sha256": "874451526b205dd0018a8f7a27a53a886a892e57b56fedd7fc3b9fa0112e2381",
          "sha1": "fa6584b836c4caa5b4c37221d197bf7abd61e5d5",
          "md5": "f49beb2f42c8380c7a2f13fd97c68a0a"
        }
      ]
    }
  ]
}
