{
  "formatVersion": "1.1",
  "component": {
    "url": "../../miuix/0.0.1/miuix-0.0.1.module",
    "group": "top.yukonga.miuix.kmp",
    "module": "miuix",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20-RC2"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-desktop-0.0.1.jar",
          "url": "miuix-desktop-0.0.1.jar",
          "size": 375762,
          "sha512": "cac3b46d2f385ac43495af608f5bf45a0edb67f646ab3726f4a61b9065ba2681f86dcdd2ad4610b183b2bee3805674356e06b2735704be4bdfd455a8e13345b3",
          "sha256": "48f2dd5b8c97bd75523916e9aa56fc7c8729d9b5fdb38729d5f28375e1edd259",
          "sha1": "5749170783d338fa348e754cfd1dfd905e8146ad",
          "md5": "7919475b0b848c194f393452f541a71c"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20-RC2"
          }
        },
        {
          "group": "org.jetbrains.compose.desktop",
          "module": "desktop-jvm-macos-arm64",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "dev.chrisbanes.haze",
          "module": "haze",
          "version": {
            "requires": "0.9.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-desktop-0.0.1.jar",
          "url": "miuix-desktop-0.0.1.jar",
          "size": 375762,
          "sha512": "cac3b46d2f385ac43495af608f5bf45a0edb67f646ab3726f4a61b9065ba2681f86dcdd2ad4610b183b2bee3805674356e06b2735704be4bdfd455a8e13345b3",
          "sha256": "48f2dd5b8c97bd75523916e9aa56fc7c8729d9b5fdb38729d5f28375e1edd259",
          "sha1": "5749170783d338fa348e754cfd1dfd905e8146ad",
          "md5": "7919475b0b848c194f393452f541a71c"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "miuix-desktop-0.0.1-sources.jar",
          "url": "miuix-desktop-0.0.1-sources.jar",
          "size": 57116,
          "sha512": "d2f84ca6be85e17742165633b1e0d244e7fc2b686d977210e1185c7838f79254a50bed71d8e949bfcc183da35bf965fbad60ed9f902b55b7b4567027e2557e57",
          "sha256": "8099b6575d67c7866b0781a79750b31d8f1a8e7a249f311536d5632cdc182e08",
          "sha1": "02d8bc89ee286f4ec326b9574fef86a724c4a363",
          "md5": "b883d41f4874728bdf7c8953e8479e75"
        }
      ]
    }
  ]
}
