{
  "formatVersion": "1.1",
  "component": {
    "url": "../../miuix/0.0.1/miuix-0.0.1.module",
    "group": "top.yukonga.miuix.kmp",
    "module": "miuix",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20-RC2"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-wasm-js-0.0.1.klib",
          "url": "miuix-wasm-js-0.0.1.klib",
          "size": 304628,
          "sha512": "60d1b758085f1c88d5ca8ce9073b737efb32798322d0d183911f4d9eb8cb814e275ce377bde6ae98f080be73f8acf61778501778b406647951c7fb59698d74b2",
          "sha256": "561fe2be6e369cf60ee9492b16634f2c3283e77419fbb53a1951b28625b4d1bf",
          "sha1": "84dea8347e94d557af2461536f4ea586ec223273",
          "md5": "e2b76bb393710f27596ab22275b89f5a"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20-RC2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "dev.chrisbanes.haze",
          "module": "haze",
          "version": {
            "requires": "0.9.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-wasm-js-0.0.1.klib",
          "url": "miuix-wasm-js-0.0.1.klib",
          "size": 304628,
          "sha512": "60d1b758085f1c88d5ca8ce9073b737efb32798322d0d183911f4d9eb8cb814e275ce377bde6ae98f080be73f8acf61778501778b406647951c7fb59698d74b2",
          "sha256": "561fe2be6e369cf60ee9492b16634f2c3283e77419fbb53a1951b28625b4d1bf",
          "sha1": "84dea8347e94d557af2461536f4ea586ec223273",
          "md5": "e2b76bb393710f27596ab22275b89f5a"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "miuix-wasm-js-0.0.1-sources.jar",
          "url": "miuix-wasm-js-0.0.1-sources.jar",
          "size": 56989,
          "sha512": "9f6b7f741a9e567400540899e60f4e451735f91ff3f7eacfdfb890b5dbda70558ca5ef3ae1773ffeebbdc5b3d5591ad3ace367e132735dfcb58ed3c7faf3eb35",
          "sha256": "89d3a9c598042ef31876530be174d2de013955007e8dd0b1f56deb29b608d07e",
          "sha1": "34bd1d7d0fd5d16e30429bcda30f76848b398629",
          "md5": "ab50e2a5ae8e8ade2b260126b6304197"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20-RC2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "dev.chrisbanes.haze",
          "module": "haze",
          "version": {
            "requires": "0.9.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-0.0.1.kotlin_resources.zip",
          "url": "miuix-wasm-js-0.0.1-kotlin_resources.kotlin_resources.zip",
          "size": 2826,
          "sha512": "307fe6adbd443494a30526aa93aa807570a36df7fc21c7785a4452da7cbc061d966c7fe1accbddcac61621688c550da0f483ccc30ecd1b5f6d7a754038df5ac8",
          "sha256": "4495197122248b7f4940eb0c61790b038d20915a4ffb9fff84d1324b961d17ad",
          "sha1": "d0b9a6040a5ecbf0119ff985fbf427f5750d3e07",
          "md5": "ae2e239766b41d96047d8704178ba607"
        }
      ]
    }
  ]
}
