{
  "formatVersion": "1.1",
  "component": {
    "url": "../../miuix/0.0.1/miuix-0.0.1.module",
    "group": "top.yukonga.miuix.kmp",
    "module": "miuix",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20-RC2"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-wasm-js-0.0.1.klib",
          "url": "miuix-wasm-js-0.0.1.klib",
          "size": 284403,
          "sha512": "be96173f820f58b5a988b099562de7e440c2fff489c523ba983bc3261c983fde4067d44e8f2d526560c6c9467995e6c1fb0a0aa68c6a11db55bfe849b7547454",
          "sha256": "ddfb5f80de6c55ac4eebc65ffa1818da5b7f37e4de7e7aceaf1b0d2d008194f2",
          "sha1": "47c3b692d839779f01c6d379267e51201aeaf2b0",
          "md5": "6899bd79249540a2368e326040f45120"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20-RC2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "dev.chrisbanes.haze",
          "module": "haze",
          "version": {
            "requires": "0.9.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-wasm-js-0.0.1.klib",
          "url": "miuix-wasm-js-0.0.1.klib",
          "size": 284403,
          "sha512": "be96173f820f58b5a988b099562de7e440c2fff489c523ba983bc3261c983fde4067d44e8f2d526560c6c9467995e6c1fb0a0aa68c6a11db55bfe849b7547454",
          "sha256": "ddfb5f80de6c55ac4eebc65ffa1818da5b7f37e4de7e7aceaf1b0d2d008194f2",
          "sha1": "47c3b692d839779f01c6d379267e51201aeaf2b0",
          "md5": "6899bd79249540a2368e326040f45120"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20-RC2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "dev.chrisbanes.haze",
          "module": "haze",
          "version": {
            "requires": "0.9.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-0.0.1.kotlin_resources.zip",
          "url": "miuix-wasm-js-0.0.1-kotlin_resources.kotlin_resources.zip",
          "size": 2826,
          "sha512": "307fe6adbd443494a30526aa93aa807570a36df7fc21c7785a4452da7cbc061d966c7fe1accbddcac61621688c550da0f483ccc30ecd1b5f6d7a754038df5ac8",
          "sha256": "4495197122248b7f4940eb0c61790b038d20915a4ffb9fff84d1324b961d17ad",
          "sha1": "d0b9a6040a5ecbf0119ff985fbf427f5750d3e07",
          "md5": "ae2e239766b41d96047d8704178ba607"
        }
      ]
    }
  ]
}
