{
  "formatVersion": "1.1",
  "component": {
    "url": "../../miuix/0.0.1/miuix-0.0.1.module",
    "group": "top.yukonga.miuix.kmp",
    "module": "miuix",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20-RC2"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-wasm-js-0.0.1.klib",
          "url": "miuix-wasm-js-0.0.1.klib",
          "size": 303538,
          "sha512": "8a0c6031df6398ebe9181d3fab0828c1dd5e531a458c305a6e9a5230325e903872ed3f6794f1bf2b626a72491835e93de56a1d65b5dcd918d0b800f9213bbf15",
          "sha256": "7566a314ef621413c11bf667dc47c642f35fc241b5dd2cfa5cf18d935c4ea0fb",
          "sha1": "a30375016878eb1e2b2ce8115c9a20f71affa97c",
          "md5": "88f90461406d3a8fe4d3cec5e2424ad4"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20-RC2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "dev.chrisbanes.haze",
          "module": "haze",
          "version": {
            "requires": "0.9.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-wasm-js-0.0.1.klib",
          "url": "miuix-wasm-js-0.0.1.klib",
          "size": 303538,
          "sha512": "8a0c6031df6398ebe9181d3fab0828c1dd5e531a458c305a6e9a5230325e903872ed3f6794f1bf2b626a72491835e93de56a1d65b5dcd918d0b800f9213bbf15",
          "sha256": "7566a314ef621413c11bf667dc47c642f35fc241b5dd2cfa5cf18d935c4ea0fb",
          "sha1": "a30375016878eb1e2b2ce8115c9a20f71affa97c",
          "md5": "88f90461406d3a8fe4d3cec5e2424ad4"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "miuix-wasm-js-0.0.1-sources.jar",
          "url": "miuix-wasm-js-0.0.1-sources.jar",
          "size": 56892,
          "sha512": "235a7fdd3716e2a13f090687a8d00f12c786a3faae1e808be100d15f3397ba426cabfaa94793a11dd19fbc25f652dfbf863cbb89ed229c3f49f5c84a07993326",
          "sha256": "841815ff4b7588d059ab86e63f7606fea11cf522ce5b14ddbe6611faaf5f3033",
          "sha1": "ed3ccac3690354e5c2102e90137194550437997c",
          "md5": "6a924ae7a18bf28bf487aa5b8648f899"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20-RC2"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "dev.chrisbanes.haze",
          "module": "haze",
          "version": {
            "requires": "0.9.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-0.0.1.kotlin_resources.zip",
          "url": "miuix-wasm-js-0.0.1-kotlin_resources.kotlin_resources.zip",
          "size": 2826,
          "sha512": "307fe6adbd443494a30526aa93aa807570a36df7fc21c7785a4452da7cbc061d966c7fe1accbddcac61621688c550da0f483ccc30ecd1b5f6d7a754038df5ac8",
          "sha256": "4495197122248b7f4940eb0c61790b038d20915a4ffb9fff84d1324b961d17ad",
          "sha1": "d0b9a6040a5ecbf0119ff985fbf427f5750d3e07",
          "md5": "ae2e239766b41d96047d8704178ba607"
        }
      ]
    }
  ]
}
