package top.yukonga.updater.buildlogic

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.Optional
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction

@CacheableTask
abstract class GenerateVersionInfoTask : DefaultTask() {
    @get:Input
    abstract val versionName: Property<String>

    @get:Input
    abstract val versionCode: Property<Int>

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @get:Optional
    @get:OutputFile
    abstract val xcconfigFile: RegularFileProperty

    @TaskAction
    fun generate() {
        val file = outputDirectory.file("misc/VersionInfo.kt").get().asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            package misc

            object VersionInfo {
                const val VERSION_NAME = "${versionName.get()}"
                const val VERSION_CODE = ${versionCode.get()}
            }
            """.trimIndent(),
        )

        xcconfigFile.orNull?.asFile?.let { xcconfig ->
            xcconfig.parentFile.mkdirs()
            xcconfig.writeText(
                """
                // Auto-generated by GenerateVersionInfoTask. DO NOT EDIT.
                MARKETING_VERSION = ${versionName.get()}
                CURRENT_PROJECT_VERSION = ${versionCode.get()}
                """.trimIndent() + "\n",
            )
        }
    }
}
