name: Build Example App

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, ubuntu-24.04-arm, windows-latest]
        include:
          - os: macos-latest
            platform: macos arm64
            build-command: ./gradlew packageDmgNativeReleaseMacosArm64
            artifact-path: macos/build/compose/binaries/main/native-macosArm64-release-dmg/*.dmg
            artifact-name: Updater-darwin-arm64-dmg.dmg
            archive: false
          - os: ubuntu-latest
            platform: linux x64
            platformEx: android universal
            build-command: ./gradlew createReleaseDistributable
            build-commandEx: ./gradlew assembleDebug && ./gradlew assembleRelease
            artifact-path: desktop/build/compose/binaries/main-release/app/Updater
            artifact-pathEx: android/build/outputs/apk/release/*.apk
            artifact-name: Updater-linux-x64-bin
            artifact-nameEx: Updater-android-universal-apk.apk
            archive: true
          - os: ubuntu-24.04-arm
            platform: linux arm64
            build-command: ./gradlew createReleaseDistributable
            artifact-path: desktop/build/compose/binaries/main-release/app/Updater
            artifact-name: Updater-linux-arm64-bin
            archive: true
          - os: windows-latest
            platform: windows x64
            build-command: ./gradlew createReleaseDistributable
            artifact-path: desktop/build/compose/binaries/main-release/app/Updater
            artifact-name: Updater-windows-x64-exe
            archive: true
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: "21"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Decode android signing key
        if: matrix.platformEx == 'android universal'
        run: echo ${{ secrets.SIGNING_KEY }} | base64 -d > keystore.jks
      - name: Build ${{ matrix.platform }} platform
        run: ${{ matrix.build-command }}
      - name: Build ${{ matrix.platformEx }} platform
        if: matrix.platformEx == 'android universal'
        run: ${{ matrix.build-commandEx }}
        env:
          KEYSTORE_PATH: "../keystore.jks"
          KEYSTORE_PASS: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      - name: Rename ${{ matrix.platform }} artifact
        run: mv ${{ matrix.artifact-path }} ${{ matrix.artifact-name }}
        shell: bash
      - name: Rename ${{ matrix.platformEx }} artifact
        if: matrix.platformEx == 'android universal'
        run: mv ${{ matrix.artifact-pathEx }} ${{ matrix.artifact-nameEx }}
        shell: bash
      - name: Upload Updater ${{ matrix.platform }} artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.artifact-name }}
          path: ${{ matrix.artifact-name }}
          archive: ${{ matrix.archive }}
      - name: Upload Updater ${{ matrix.platformEx }} artifact
        if: matrix.platformEx == 'android universal'
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.artifact-nameEx }}
          path: ${{ matrix.artifact-nameEx }}
          archive: false

  post_telegram:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ success() && github.event_name != 'pull_request' && github.ref == 'refs/heads/main' && github.ref_type != 'tag' }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Get commit count
        id: commit_count
        run: echo "count=$(git rev-list --count HEAD)" >> $GITHUB_OUTPUT

      - name: Download all artifacts
        uses: actions/download-artifact@v8
        with:
          path: artifacts

      - name: Post to Telegram ci channel
        env:
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          BOT_API_LINK: ${{ secrets.BOT_API_LINK }}
          COMMIT_COUNT: ${{ steps.commit_count.outputs.count }}
          COMMIT_MESSAGE: |+
            New CI from Updater-KMP (${{ steps.commit_count.outputs.count }})

            ${{ github.event.head_commit.message }}
        run: bash .github/scripts/post_telegram.sh
